homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 59.3247
  longitude: 18.056
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 3
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

logger:
  default: info
  logs:
    homeassistant.components.enocean: debug
    homeassistant.components.rfxtrx: debug
    
http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

group: !include groups.yaml
    
enocean:
  device: COM5

rfxtrx:
  device: COM4

switch:
  - platform: enocean
    id: [0x00,0x00,0x13,0x15]
    sender_id: [0xFF,0xF3,0x45,0x81]
    name: Sw1
    type: FT55
  - platform: enocean
    id: [0x00,0x00,0x13,0x15]
    sender_id: [0xFF,0xAB,0xFC,0x82]
    name: Sw2
    type: switch
  - platform: enocean
    id: [0x00,0x00,0x13,0x15]
    sender_id: [0xFF,0xAB,0xFC,0x83]
    channel: 1
    name: Sw3-1
    type: switch
  - platform: enocean
    id: [0x00,0x00,0x13,0x15]
    sender_id: [0xFF,0xAB,0xFC,0x83]
    channel: 2
    name: Sw3-2
    type: switch

light:
  - platform: enocean
    id: [0xFF,0x9D,0x13,0x15]
    sender_id: [0xFF,0xF3,0x45,0x81]

sensor:
  - platform: yr
  - platform: enocean
    name: "Elcentral"
    id: [0xFF,0x9D,0x13,0x35]
  - platform: enocean
    name: "Ljus Ute"
    id: [0x00,0x86,0x11,0x61]
    type: light

binary_sensor:
  - platform: enocean
    name: "En1"
    id: [0x00,0x8A,0xCE,0x64]

    